# SPDX-License-Identifier: GPL-3.0-only
"""Turning facts into a document.

Every line here comes from something a tool produced: ports from the AST,
prose from the header the author wrote, pins from the fitter, timing from the
timing analyser. Where a fact is missing the document says so and moves on.
Nothing is inferred, because a reference that guesses is worse than one with a
gap -- the gap is visible and the guess is not.
"""

from dataclasses import dataclass, field
from typing import Any

from .. import __version__
from ..index.model import Module
from ..quartus.reports import Message, Reports
from .constraints import Clock, Pin
from .document import Block, Bullets, Diagram, Heading, Paragraph, Table

#: Marks the document as machine-written. Carries no timestamp on purpose:
#: a generated file that changes on every run cannot be committed as a
#: sample, and cannot be diffed to see whether the design changed.
PROVENANCE = (
    f"Generated by WEFT {__version__} from the project's sources, constraints "
    "and reports. Regenerate it rather than editing it."
)

#: Said where a compilation would have supplied the numbers and has not run.
NOT_COMPILED = "No compilation reports were found, so resources and timing are absent."


@dataclass
class Project:
    """What a project document is built from.

    Each field is optional because each comes from a step the user may not
    have taken. A design that has never been fitted still documents its ports
    and its hierarchy; it simply has no pin map.

    @name: revision name
    @info: the .qsf's own summary, as project_info() returns it
    @modules: everything indexed, in name order
    @top: the top entity's hierarchy tree, or None when it is not indexed
    @pins / @clocks: the constraints
    @reports: parsed compilation reports, or None
    """

    name: str
    info: dict[str, Any] = field(default_factory=dict)
    modules: list[Module] = field(default_factory=list)
    top: dict[str, Any] | None = None
    pins: list[Pin] = field(default_factory=list)
    clocks: list[Clock] = field(default_factory=list)
    reports: Reports | None = None


def module_doc(module: Module, instantiated_by: list[str] | None = None) -> list[Block]:
    """module_doc - one module's reference page

    @module: as the index holds it
    @instantiated_by: modules that instantiate this one

    Return: the blocks of the document.
    """
    blocks: list[Block] = [Heading(1, module.name), Paragraph(PROVENANCE)]

    if module.summary:
        blocks.append(Paragraph(module.summary))
    if module.description:
        blocks.append(Paragraph(module.description))

    blocks.append(Paragraph(f"Defined in `{module.file}:{module.line}` ({module.language})."))

    if module.parameters:
        blocks += [
            Heading(2, "Parameters"),
            Table(
                ["Name", "Type", "Default", "Description"],
                [[p.name, p.type or "", p.default or "", p.doc or ""] for p in module.parameters],
            ),
        ]

    if module.ports:
        blocks += [
            Heading(2, "Ports"),
            Table(
                ["Name", "Direction", "Type", "Description"],
                [[p.name, p.direction, p.type, p.doc or ""] for p in module.ports],
            ),
        ]

    if module.instances:
        blocks += [
            Heading(2, "Instances"),
            Table(
                ["Instance", "Module", "Line"],
                [[i.name, i.of, str(i.line)] for i in module.instances],
            ),
        ]

    if instantiated_by:
        blocks += [Heading(2, "Instantiated by"), Bullets(sorted(instantiated_by))]

    return blocks


def project_doc(project: Project) -> list[Block]:
    """project_doc - the project's reference document

    @project: the facts gathered for it

    Return: the blocks of the document, in reading order: what the project is,
    how it is built, where its signals go, and how it came out.
    """
    blocks: list[Block] = [Heading(1, project.name), Paragraph(PROVENANCE)]
    blocks += _overview(project)
    blocks += _hierarchy(project)
    blocks += _modules(project)
    blocks += _clocks(project)
    blocks += _pins(project)
    blocks += _results(project)
    return blocks


def _overview(project: Project) -> list[Block]:
    """_overview - device, top entity and source counts."""
    info = project.info
    rows = [
        ["Revision", project.name],
        ["Top entity", info.get("top_entity", "")],
        ["Family", info.get("family", "")],
        ["Device", info.get("device", "")],
    ]
    sources = info.get("sources") or {}
    for language, files in sorted(sources.items()):
        rows.append([f"{language} sources", str(len(files))])

    return [Heading(2, "Overview"), Table(["", ""], rows)]


def _hierarchy(project: Project) -> list[Block]:
    """_hierarchy - the instance tree, drawn."""
    if project.top is None:
        return []
    return [Heading(2, "Hierarchy"), Diagram(project.top)]


def _modules(project: Project) -> list[Block]:
    """_modules - one line per module, with the summary its author wrote."""
    if not project.modules:
        return []
    return [
        Heading(2, "Modules"),
        Table(
            ["Module", "Language", "Summary", "File"],
            [[m.name, m.language, m.summary or "", m.file] for m in project.modules],
        ),
    ]


def _clocks(project: Project) -> list[Block]:
    """_clocks - the constrained clock domains."""
    if not project.clocks:
        return []
    return [
        Heading(2, "Clocks"),
        Table(
            ["Clock", "Period (ns)", "Frequency (MHz)", "Target", "Source"],
            [
                [
                    c.name,
                    _number(c.period_ns),
                    _number(c.frequency_mhz),
                    c.target or "",
                    f"{c.file}{' (generated)' if c.generated else ''}",
                ]
                for c in project.clocks
            ],
        ),
    ]


def _pins(project: Project) -> list[Block]:
    """_pins - the pin map, and where it came from."""
    if not project.pins:
        return []

    chosen = sum(1 for p in project.pins if not p.assigned)
    blocks: list[Block] = [Heading(2, "Pin map")]
    if chosen:
        blocks.append(
            Paragraph(
                f"{chosen} of {len(project.pins)} signals were placed by the fitter rather "
                "than constrained; those locations change whenever the design is refitted."
            )
        )
    blocks.append(
        Table(
            ["Signal", "Pin", "Direction", "I/O standard", "Bank", "Assigned"],
            [
                [
                    p.signal,
                    p.location,
                    p.direction or "",
                    p.io_standard or "",
                    p.bank or "",
                    "yes" if p.assigned else "no",
                ]
                for p in project.pins
            ],
        )
    )
    return blocks


def _results(project: Project) -> list[Block]:
    """_results - resources and timing, when a compilation produced them."""
    reports = project.reports
    if reports is None:
        return [Heading(2, "Compilation results"), Paragraph(NOT_COMPILED)]

    blocks: list[Block] = [Heading(2, "Compilation results")]
    if reports.status:
        blocks.append(Paragraph(f"Status: {reports.status}"))

    if reports.resources:
        blocks += [
            Heading(3, "Resources"),
            Table(
                ["Resource", "Used", "Available", "%"],
                [
                    [
                        name,
                        str(usage.used),
                        "" if usage.available is None else str(usage.available),
                        _number(usage.percent),
                    ]
                    for name, usage in reports.resources.items()
                ],
            ),
        ]

    if reports.timing:
        blocks += [
            Heading(3, "Timing"),
            Table(
                ["Clock", "Fmax (MHz)", "Restricted Fmax (MHz)", "Worst slack (ns)", "Met"],
                [
                    [
                        t.clock,
                        _number(t.fmax_mhz),
                        _number(t.restricted_fmax_mhz),
                        _number(min(t.slack.values()) if t.slack else None),
                        "yes" if t.met else "no",
                    ]
                    for t in reports.timing
                ],
            ),
        ]

    if reports.message_count:
        blocks.append(
            Paragraph(
                f"{reports.message_count} warnings and errors were reported; "
                "parse_reports returns them ranked."
            )
        )
    return blocks


def _number(value: float | None) -> str:
    """_number - a figure without a trailing .0, or nothing at all."""
    if value is None:
        return ""
    if float(value).is_integer():
        return str(int(value))
    return f"{value:g}"


def compilation_doc(revision: str, reports: Reports) -> list[Block]:
    """compilation_doc - what one compilation produced, developer first

    @revision: revision name, for the title
    @reports: the parsed reports

    A separate document from the project reference on purpose. The reference
    changes when the design changes; this changes every time the flow runs,
    and a build worth keeping is a build whose report can be kept beside it.

    It opens with the three things a developer wants before anything else --
    did it build, did timing close, what should be looked at -- because a
    summary that leads with a resource table makes those three the reader's
    job to work out. Everything else is below, in the order it is usually
    needed.

    Return: the blocks of the document.
    """
    return [
        Heading(1, f"{revision} — compilation"),
        Paragraph(PROVENANCE),
        *_verdict(reports),
        *_attention(reports),
        *_resources(reports),
        *_timing_detail(reports),
        *_other_messages(reports),
        *_provenance(reports),
    ]


def _verdict(reports: Reports) -> list[Block]:
    """_verdict - the answer, before the evidence.

    One line a reader can stop at, and a table for the numbers behind it.
    """
    closed = [t for t in reports.timing if t.met]
    peak = max(
        (u.percent for u in reports.resources.values() if u.percent is not None), default=None
    )

    said = [f"Status: {reports.status}." if reports.status else "The flow reported no status."]
    if reports.timing:
        said.append(
            f"Timing met on {len(closed)} of {len(reports.timing)} "
            f"clock{'s' if len(reports.timing) != 1 else ''}."
        )
    else:
        said.append("No timing analysis was found.")
    said.append(_severity_phrase(reports))

    rows = [
        ["Device", reports.device or ""],
        ["Top entity", reports.top_entity or ""],
    ]
    if peak is not None:
        rows.append(["Fullest resource", f"{_number(peak)} %"])
    if reports.timing:
        rows.append(["Worst slack", _worst_slack(reports)])
        rows.append(["Lowest Fmax", _fmax_floor(reports)])
    rows.append(["Messages", _message_tally(reports)])

    return [Heading(2, "Verdict"), Paragraph(" ".join(said)), Table(["", ""], rows)]


def _errors(reports: Reports) -> list[Message]:
    """_errors - messages Quartus called an error."""
    return [m for m in reports.messages if "error" in m.severity.lower()]


def _critical(reports: Reports) -> list[Message]:
    """_critical - messages Quartus called a critical warning."""
    return [m for m in reports.messages if "critical" in m.severity.lower()]


def _severity_phrase(reports: Reports) -> str:
    """_severity_phrase - what rose above an ordinary warning, named correctly

    Errors and critical warnings are not the same thing and must not be
    counted together: a build with two critical warnings and no errors is a
    build that succeeded, and saying "2 errors" about it is simply false.
    """
    errors, critical = len(_errors(reports)), len(_critical(reports))
    parts = []
    if errors:
        parts.append(f"{errors} error{'s' if errors != 1 else ''}")
    if critical:
        parts.append(f"{critical} critical warning{'s' if critical != 1 else ''}")
    if not parts:
        return "Nothing rose above an ordinary warning."
    return f"{' and '.join(parts)} to look at."


def _message_tally(reports: Reports) -> str:
    """_message_tally - the message counts, broken out by what they are."""
    errors, critical = len(_errors(reports)), len(_critical(reports))
    return f"{reports.message_count} total, {errors} error, {critical} critical"


def _worst_slack(reports: Reports) -> str:
    """_worst_slack - the tightest slack, and which check it belongs to

    Naming the check matters. The smallest number is often hold, and a reader
    shown a bare "0.144 ns" reads it as setup and concludes the design is
    nearly out of speed when it is nowhere near.
    """
    found = [
        (slack, check, timing.clock)
        for timing in reports.timing
        for check, slack in timing.slack.items()
    ]
    if not found:
        return ""
    slack, check, clock = min(found)
    return f"{_number(slack)} ns ({check}, {clock})"


def _fmax_floor(reports: Reports) -> str:
    """_fmax_floor - the slowest clock's Fmax, which is the design's ceiling."""
    found = [t.fmax_mhz for t in reports.timing if t.fmax_mhz is not None]
    if not found:
        return ""
    slowest = min(found)
    clock = next(t.clock for t in reports.timing if t.fmax_mhz == slowest)
    return f"{_number(slowest)} MHz ({clock})"


def _attention(reports: Reports) -> list[Block]:
    """_attention - errors and critical warnings, on their own

    Kept apart from the ordinary warnings because they do not belong in the
    same list: a compilation prints boilerplate about thermal models and
    licence features every single time, and burying two critical warnings in
    six lines of it is how they get missed.
    """
    serious = [m for m in reports.messages if _serious(m)]
    if not serious:
        return [Heading(2, "Needs attention"), Paragraph("No errors and no critical warnings.")]

    return [
        Heading(2, "Needs attention"),
        Table(
            ["Severity", "ID", "Message", "Report"],
            [[m.severity, m.code, m.text, m.source] for m in serious],
        ),
    ]


def _serious(message: Message) -> bool:
    """_serious - whether a message is one a developer has to read."""
    return "error" in message.severity.lower() or "critical" in message.severity.lower()


def _resources(reports: Reports) -> list[Block]:
    """_resources - the resource lines, as the fitter counted them."""
    if not reports.resources:
        return []
    return [
        Heading(2, "Resources"),
        Table(
            ["Resource", "Used", "Available", "%"],
            [
                [
                    name,
                    str(usage.used),
                    "" if usage.available is None else str(usage.available),
                    _number(usage.percent),
                ]
                for name, usage in reports.resources.items()
            ],
        ),
    ]


def _timing_detail(reports: Reports) -> list[Block]:
    """_timing_detail - every check of every clock, not just the worst one

    The project reference shows the worst slack per clock, which answers "did
    it close". This answers "where is it tight", which is the question asked
    next, and the two are not the same number: a clock can meet setup
    comfortably and fail recovery.
    """
    if not reports.timing:
        return []

    checks = sorted({c for t in reports.timing for c in t.slack})
    rows = []
    for timing in reports.timing:
        row = [timing.clock, _number(timing.fmax_mhz), _number(timing.restricted_fmax_mhz)]
        for check in checks:
            slack = timing.slack.get(check)
            row.append("" if slack is None else f"{slack:g} / {_number(timing.tns.get(check))}")
        row.append("yes" if timing.met else "no")
        rows.append(row)

    header = ["Clock", "Fmax (MHz)", "Restricted (MHz)"]
    header += [f"{check}: slack / TNS (ns)" for check in checks]
    header += ["Met"]
    return [Heading(2, "Timing"), Table(header, rows)]


def _other_messages(reports: Reports) -> list[Block]:
    """_other_messages - the ordinary warnings, below the ones that matter."""
    ordinary = [m for m in reports.messages if not _serious(m)]
    if not ordinary:
        return []

    blocks: list[Block] = [Heading(2, "Other warnings")]
    hidden = reports.message_count - len(reports.messages)
    if hidden > 0:
        blocks.append(
            Paragraph(
                f"{reports.message_count} messages in total; {hidden} are not listed here. "
                "The full text is in the reports on disk."
            )
        )
    blocks.append(
        Table(
            ["Severity", "ID", "Message", "Report"],
            [[m.severity, m.code, m.text, m.source] for m in ordinary],
        )
    )
    return blocks


def _provenance(reports: Reports) -> list[Block]:
    """_provenance - which report files these figures were read out of."""
    if not reports.files:
        return []
    return [
        Heading(2, "Sources"),
        Bullets([f"`{name}`" for name in sorted(reports.files)]),
        Paragraph(
            f"Compiled with Quartus {reports.quartus_version}."
            if reports.quartus_version
            else "The reports do not name a Quartus version."
        ),
    ]
