# SPDX-License-Identifier: GPL-3.0-only
"""Pages built from the code rather than written beside it.

A hand-written list of the server's tools disagrees with the server by the
next milestone, and a hand-written list of configuration keys disagrees with
the loader sooner than that. Both are read from the source here, so a tool
that is added or a key that is renamed shows up in the documentation without
anybody remembering to do it.
"""

import ast
import asyncio
import tempfile
from pathlib import Path

HEADER = "<!-- Generated by Documentation/generate.py. Do not edit. -->\n\n"


def write(directory: Path) -> None:
    """write - refresh every generated page under @directory."""
    (directory / "tools.md").write_text(HEADER + _tools())
    (directory / "configuration.md").write_text(HEADER + _configuration())


def _tools() -> str:
    """_tools - the reference for every tool the server registers.

    The server is built against a throwaway workspace, because building it is
    the only way to ask it what it exposes -- the tools are registered by
    decorators inside build(), not listed anywhere a parser could read.
    """
    from weft.config import Config, Http
    from weft.server import build

    with tempfile.TemporaryDirectory() as scratch:
        root = Path(scratch)
        config = Config(
            workspace=root,
            image="weft-tools",
            quartus={},
            edition=None,
            questa=None,
            jobs_db=root / "jobs.sqlite",
            job_timeout_s=7200,
            rag_db=root / "documents.sqlite",
            rag_library=root,
            rag_model=None,
            http=Http(),
        )
        found = asyncio.run(build(config).list_tools())

    lines = [
        "# Tools",
        "",
        "Every tool the server exposes, as an MCP client sees it. Paths in",
        "arguments are relative to the configured workspace root, and anything",
        "resolving outside it is refused.",
        "",
    ]
    for tool in sorted(found, key=lambda t: t.name):
        lines += [f"## `{tool.name}`", "", (tool.description or "").strip(), ""]
        arguments = _arguments(tool)
        if arguments:
            lines += ["| Argument | Type | Required |", "|---|---|---|", *arguments, ""]
    return "\n".join(lines) + "\n"


def _arguments(tool: object) -> list[str]:
    """_arguments - one table row per argument of a tool."""
    schema = getattr(tool, "input_schema", None) or {}
    required = set(schema.get("required", []))
    rows = []
    for name, spec in (schema.get("properties") or {}).items():
        rows.append(f"| `{name}` | {_type(spec)} | {'yes' if name in required else 'no'} |")
    return rows


def _type(spec: dict) -> str:
    """_type - a JSON Schema type as one readable word."""
    if "type" in spec:
        return str(spec["type"])
    for key in ("anyOf", "oneOf"):
        if key in spec:
            return " or ".join(_type(s) for s in spec[key] if s.get("type") != "null")
    return "any"


def _configuration() -> str:
    """_configuration - every key the loader accepts, read from the loader.

    The keys come from the _reject_unknown() calls in config.py, which are the
    same lists that decide what is refused at startup. Documenting them from
    anywhere else would let the two disagree, and the loader would win.
    """
    source = Path(__file__).resolve().parent.parent / "src" / "weft" / "config.py"
    tree = ast.parse(source.read_text())

    tables: dict[str, list[str]] = {}
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and getattr(node.func, "id", "") == "_reject_unknown"):
            continue
        if len(node.args) != 3 or not isinstance(node.args[2], ast.Constant):
            continue
        keys = [k.value for k in node.args[1].elts if isinstance(k, ast.Constant)]
        tables[str(node.args[2].value)] = sorted(keys)

    lines = [
        "# Configuration",
        "",
        "WEFT reads one TOML file, by default `~/.config/weft/weft.toml`.",
        "Unknown keys are refused rather than ignored, so a typo fails at",
        "startup instead of quietly doing nothing.",
        "",
        "The tables below are read out of the loader itself, so they are the",
        "keys it actually accepts.",
        "",
    ]
    for table, keys in sorted(tables.items()):
        title = "Top level" if table == "top level" else f"`[{table}]`"
        lines += [f"## {title}", "", *[f"- `{key}`" for key in keys], ""]

    lines += [
        "## A complete example",
        "",
        "```{eval-rst}",
        ".. literalinclude:: example.toml",
        "   :language: toml",
        "```",
        "",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    write(Path(__file__).resolve().parent)
    print("wrote tools.md and configuration.md")
